Repository TokTok/experimental, pull requests merged in 2025-02, with the labels that each got.

#62 feat: Build netlify previews on github actions.
  .github/workflows/pages.yml
  .github/workflows/release.yml
  .netlify/build.sh
  .netlify/state.json
Labels: enhancement

#64 chore: Use master build script but PR data.
  .github/workflows/release.yml
Labels: chore

#65 fix: Use correct note format in comment.
  .github/workflows/release.yml
Labels: bug

#66 fix: Grep out the correct URL from preview deploys.
  .github/workflows/release.yml
Labels: bug

#68 feat: Make a comment both at the start and at the end of build.
  .github/workflows/release.yml
Labels: enhancement

#69 fix: Use Docker for security in building the web deploy.
  .github/workflows/release.yml
  .netlify/Dockerfile
  .netlify/build.sh
Labels: bug

#70 cleanup: Use green tip for success.
  .github/workflows/release.yml
  .netlify/Dockerfile
Labels: cleanup

#72 chore: Use common workflow for netlify build.
  .github/workflows/release.yml
Labels: chore

#73 chore: Use the TokTok version of netlify workflow.
  .github/workflows/release.yml
Labels: chore

#78 feat: Add another sentence to the hello world.
  .netlify/Dockerfile
Labels: enhancement

#80 chore: Add changelog for release.
  .clog.toml
  CHANGELOG.md
Labels: chore

#81 chore: Release v0.1.1
  CHANGELOG.md
Labels: chore

#82 feat: Add a "binary" (actually text) deploy workflow.
  .github/workflows/deploy.yml
Labels: enhancement

#83 feat: Add release workflow.
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  .github/workflows/draft.yml
  .github/workflows/pages.yml
  .github/workflows/release.yml
Labels: enhancement

#84 chore: Add release tracking issue template.
  .github/ISSUE_TEMPLATE/release.yaml
Labels: chore

#89 fix: Use dropdown instead of checkbox for release type.
  .github/ISSUE_TEMPLATE/release.yaml
Labels: bug

#92 feat: Add a "hello you" in addition to "hello world".
  .github/workflows/deploy.yml
Labels: enhancement

#94 feat: Add a file listing.
  .github/workflows/deploy.yml
Labels: enhancement

#97 feat: Add a cmake file.
  .github/workflows/deploy.yml
  .github/workflows/release.yml
  CMakeLists.txt
Labels: enhancement

#98 chore: Limit concurrency by release tracking issue number.
  .github/workflows/release.yml
Labels: chore

#101 chore: Add version update script.
  .github/workflows/ci.yml
  CMakeLists.txt
  tools/update-versions.sh
Labels: chore

#102 fix: Ignore ci-tools so we don't commit it during releases.
  third_party/.gitignore
Labels: bug

#106 chore: Test the forcibly triggering of CI on release PRs.
  .github/workflows/release.yml
  CHANGELOG.md
Labels: chore

#112 chore: Release v0.1.6-rc.1
  CHANGELOG.md
  CMakeLists.txt
Labels: chore

#113 feat: Add docker push into GitHub container registry.
  .github/workflows/docker.yml
Labels: enhancement
